package com.ai.tirios.dataclasses

data class MemberX(
    val address1: String,
    val address2: Any,
    val city: String,
    val country: String,
    val created: String,
    val creator: String,
    val dl: String,
    val dlState: String,
    val dob: String,
    val email: String,
    val fax: String,
    val first: String,
    val frozen: Int,
    val gender: Any,
    val id: Int,
    val inactive: Int,
    val isActive: Any,
    val last: String,
    val login: Any,
    val memberId: String,
    val merchant: Any,
    val middle: Any,
    val modified: String,
    val modifier: String,
    val ownership: String,
    val phone: Any,
    val politicallyExposed: Int,
    val primary: String,
    val significantResponsibility: Int,
    val ssn: String,
    val state: String,
    val timezone: String,
    val title: String,
    val zip: String
)